import React from "react";

export const metadata: { title: string; description: string } = {
  title: "Sign Up",
  description: "Generated by create next app",
};

export function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

export default Layout;
